import {
  IconActivity,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconBarbell,
  IconBath,
  IconBed,
  IconBeer,
  IconBuildingStore,
  IconBulb,
  IconCamera,
  IconCar,
  IconChartBar,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClipboardCheck,
  IconCoffee,
  IconCoin,
  IconDesk,
  IconDots,
  IconHammer,
  IconHeart,
  IconHome,
  IconHomeDollar,
  IconHomeSearch,
  IconInfoCircle,
  IconLayoutDashboard,
  IconMapPin,
  IconMenu2,
  IconMessage,
  IconMicrophone,
  IconPaw,
  IconPlant,
  IconPlus,
  IconRefresh,
  IconScale,
  IconSchool,
  IconSearch,
  IconShieldCheck,
  IconSofa,
  IconStairsDown,
  IconSparkles,
  IconSun,
  IconTag,
  IconTags,
  IconTarget,
  IconToolsKitchen2,
  IconTrash,
  IconPencil,
  IconTrees,
  IconUser,
  IconUserPlus,
  IconUsers,
  IconVideo,
  IconWriting,
  IconX,
  type Icon as TablerIcon,
} from '@tabler/icons-react';

export const ICONS: Record<string, TablerIcon> = {
  'ti-home-search': IconHomeSearch,
  'ti-home-dollar': IconHomeDollar,
  'ti-menu-2': IconMenu2,
  'ti-home': IconHome,
  'ti-clipboard-check': IconClipboardCheck,
  'ti-chart-bar': IconChartBar,
  'ti-user': IconUser,
  'ti-layout-dashboard': IconLayoutDashboard,
  'ti-users': IconUsers,
  'ti-hammer': IconHammer,
  'ti-plus': IconPlus,
  'ti-sparkles': IconSparkles,
  'ti-refresh': IconRefresh,
  'ti-tools-kitchen-2': IconToolsKitchen2,
  'ti-sofa': IconSofa,
  'ti-bed': IconBed,
  'ti-bath': IconBath,
  'ti-stairs-down': IconStairsDown,
  'ti-plant': IconPlant,
  'ti-car': IconCar,
  'ti-desk': IconDesk,
  'ti-camera': IconCamera,
  'ti-video': IconVideo,
  'ti-microphone': IconMicrophone,
  'ti-arrow-left': IconArrowLeft,
  'ti-arrow-right': IconArrowRight,
  'ti-check': IconCheck,
  'ti-chevron-left': IconChevronLeft,
  'ti-chevron-right': IconChevronRight,
  'ti-trash': IconTrash,
  'ti-pencil': IconPencil,
  'ti-alert-triangle': IconAlertTriangle,
  'ti-message': IconMessage,
  'ti-user-plus': IconUserPlus,
  'ti-scale': IconScale,
  'ti-coin': IconCoin,
  'ti-map-pin': IconMapPin,
  'ti-search': IconSearch,
  'ti-building-store': IconBuildingStore,
  'ti-trees': IconTrees,
  'ti-school': IconSchool,
  'ti-barbell': IconBarbell,
  'ti-coffee': IconCoffee,
  'ti-info-circle': IconInfoCircle,
  'ti-tag': IconTag,
  'ti-dots': IconDots,
  'ti-writing': IconWriting,
  'ti-tags': IconTags,
  'ti-x': IconX,
  'ti-heart': IconHeart,
  'ti-bulb': IconBulb,
  'ti-sun': IconSun,
  'ti-shield-check': IconShieldCheck,
  'ti-target': IconTarget,
  'ti-activity': IconActivity,
  'ti-paw': IconPaw,
  'ti-beer': IconBeer,
};

export function getIcon(key: string): TablerIcon {
  return ICONS[key] ?? IconHome;
}
